### ISSUE TITLE
upgrading

### ISSUE THREAD

**Issue by scargill** [enebular/node-red-contrib-admin#3]
I note that as well as not really indicating when an install of a node is going on, the package also, if you try to upgrade a node, again... you don't really know if anything is happening - is it possible to put up a "working" message or a busy icon or something - some updates can take several seconds to a minute and not knowing if anything is actually happening is painful.

**Comment by syuhei176** [comment]
I added message "Installing" during installing.

**Comment by scargill** [comment]
Thanks. Are you able to update  http://flows.nodered.org/node/node-red-contrib-admin

Please.

Pete.

**Comment by syuhei176** [comment]
You're welcome. I'm not able to publish, but I already asked to owner.

**Comment by scargill** [comment]
Oh sorry – I thought you were the owner – well, I’ve added your modifications and it’s wonderful! Thanks.
